# Generated by Django 5.1.11 on 2025-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content_type',
            field=models.CharField(default='text/plain', help_text='MIME type of the message content', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL to the file if the message contains a file', max_length=500, null=True),
        ),
    ]
