# Generated by Django 5.1.11 on 2025-06-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_content_type_chatmessage_file_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userchannelstate',
            table='chat_userchannelstate',
        ),
    ]
