# Generated by Django 5.1.11 on 2025-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantusermodel',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantusermodel',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tenantusermodel',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantusermodel',
            name='status',
            field=models.CharField(blank=True, help_text="User's custom status message", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantusermodel',
            name='status_emoji',
            field=models.CharField(blank=True, help_text="Emoji representing user's status", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tenantusermodel',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
