# Generated by Django 5.1.11 on 2025-06-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_tenantusermodel_avatar_url_tenantusermodel_is_online_and_more'),
    ]

    operations = [
    ]
